site_name: JinjaPsycopg

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            merge_init_into_class: true
            show_source: true
            members_order: source
            docstring_section_style: list
          import:
            - https://docs.python.org/3/objects.inv
            - https://www.psycopg.org/psycopg3/docs/objects.inv
            - https://jinja.palletsprojects.com/en/3.1.x/objects.inv

nav:
  - Home: index.md
  - Code Reference: reference/

extra_css:
  - css/mkdocstrings.css

watch:
  - jinja_psycopg
